home/urls.py
from django.urls import path
from home import views
from .views import (
    CityWithTeams, TeamStadium,
    CityTeams,
)

app_name = "home"

urlpatterns = [
   path('', views.Index.as_view(), name='index'),

   path('equipo/', views.TeamIndex.as_view(), name='equipoindex'),
   path('equipo/', views.EquipoIndex.as_view(), name="teamindex"),
   path('equipo/<int:pk>/', views.DetailTeam.as_view(), name='equipo_detail'),
   path('equipo/new/', views.NewTeam.as_view(), name='equipo_new'),
   path('equipo/<int:pk>/edit/', views.UpdateTeam.as_view(), name='equipo_edit'),
   path('equipo/<int:pk>/delete/', views.DeleteTeam.as_view(), name='equipo_delete'),

   path('estadio/', views.StadiumIndex.as_view(), name='estadioindex'),
   path('estadio/<int:pk>/', views.DetailEstadio.as_view(), name='estadio_detail'),
   path('estadio/new/', views.NewEstadio.as_view(), name='estadio_new'),
   path('estadio/<int:pk>/edit/', views.UpdateEstadio.as_view(), name='estadio_edit'),
   path('estadio/<int:pk>/delete/', views.DeleteEstadio.as_view(), name='estadio_delete'),

   path('ciudad/', views.CityIndex.as_view(), name='ciudadindex'),
   path('ciudad/<int:pk>/', views.DetailCiudad.as_view(), name='ciudad_detail'),
   path('ciudad/new/', views.NewCiudad.as_view(), name='ciudad_new'),
   path('ciudad/<int:pk>/edit/', views.UpdateCiudad.as_view(), name='ciudad_edit'),
   path('ciudad/<int:pk>/delete/', views.DeleteCiudad.as_view(), name='ciudad_delete'),



   path('equipo/citywithteams/', CityWithTeams.as_view(), name='cityWithTeams'),
   path('equipo/teamstadium/', TeamStadium.as_view(), name='teamsStadium'),
   path('equipo/cityteams/', CityTeams.as_view(), name='cityTeams'),
]

nfl_remedial/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]

templates/base/equipoindex.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
  <div>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #b80808;">
      <a class="navbar-brand" href="#"><img style="width:5rem;  margin: 0 1rem;" src="{% static 'logo_nfl.png' %}"/></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link text-white" href="{% url 'home:equipoindex' %}">Equipos</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link text-white" href="{% url 'home:ciudadindex' %}">Ciudades</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link text-white" href="{% url 'home:estadioindex' %}">Estadios</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container" style="margin-top: 5rem;">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
</body>
</html>

templates/base/lobby.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <title>NFL</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #b80808;">
    <a class="navbar-brand" href="#"><img style="width:5rem;  margin: 0 1rem;" src="{% static 'logo_nfl.png' %}"/></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home:equipoindex' %}">Equipos</a>

        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home:ciudadindex' %}">Ciudades</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home:estadioindex' %}">Estadios</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Secciones
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'home:cityWithTeams' %}">Equipos</a>
            <a class="dropdown-item" href="{% url 'home:cityTeams' %}">Sección 2</a>
            <a class="dropdown-item" href="{% url 'home:teamsStadium' %}">Juegos</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container my-4">
    <p style="margin: 4rem 0;">La NFL es la mayor competición de fútbol americano profesional de Estados Unidos. Actualmente, es la liga deportiva que más dinero recauda a nivel mundial. Fue creada en 1920 y actualmente se divide en 32 franquicias (equipos) repartidas por todo el territorio norteamericano entre dos conferencias.</p>
    <div class="d-flex justify-content-center align-items-center">
      <img style="width: 50rem;" src="{% static 'nfl_promo.jpg' %}"/>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>