home/urls.py
from django.urls import path
from home import views
from .views import (
    CityWithTeams, TeamStadium,
    CityTeams,
)

app_name = "home"

urlpatterns = [
   path('', views.Index.as_view(), name='index'),

   path('equipo/', views.TeamIndex.as_view(), name='equipoindex'),
   path('equipo/', views.EquipoIndex.as_view(), name="teamindex"),
   path('equipo/<int:pk>/', views.DetailTeam.as_view(), name='equipo_detail'),
   path('equipo/new/', views.NewTeam.as_view(), name='equipo_new'),
   path('equipo/<int:pk>/edit/', views.UpdateTeam.as_view(), name='equipo_edit'),
   path('equipo/<int:pk>/delete/', views.DeleteTeam.as_view(), name='equipo_delete'),

   path('estadio/', views.StadiumIndex.as_view(), name='estadioindex'),
   path('estadio/<int:pk>/', views.DetailEstadio.as_view(), name='estadio_detail'),
   path('estadio/new/', views.NewEstadio.as_view(), name='estadio_new'),
   path('estadio/<int:pk>/edit/', views.UpdateEstadio.as_view(), name='estadio_edit'),
   path('estadio/<int:pk>/delete/', views.DeleteEstadio.as_view(), name='estadio_delete'),

   path('ciudad/', views.CityIndex.as_view(), name='ciudadindex'),
   path('ciudad/<int:pk>/', views.DetailCiudad.as_view(), name='ciudad_detail'),
   path('ciudad/new/', views.NewCiudad.as_view(), name='ciudad_new'),
   path('ciudad/<int:pk>/edit/', views.UpdateCiudad.as_view(), name='ciudad_edit'),
   path('ciudad/<int:pk>/delete/', views.DeleteCiudad.as_view(), name='ciudad_delete'),



   path('equipo/citywithteams/', CityWithTeams.as_view(), name='cityWithTeams'),
   path('equipo/teamstadium/', TeamStadium.as_view(), name='teamsStadium'),
   path('equipo/cityteams/', CityTeams.as_view(), name='cityTeams'),
]

nfl_remedial/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]

home/models.py
from django.db import models

class Estadio(models.Model):
    id_estadio = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name
    
class Ciudad(models.Model):
    id_ciudad = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name

class Team(models.Model):
    id_team = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80)
    city = models.ForeignKey(Ciudad, on_delete=models.CASCADE, null=True)
    stadium = models.ForeignKey(Estadio, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from .models import Team, Ciudad, Estadio

#FORM EQUIPO
class UpdateTeamForm(forms.ModelForm):
    city = forms.ModelChoiceField(queryset=Ciudad.objects.all(), required=False)
    stadium = forms.ModelChoiceField(queryset=Estadio.objects.all(), required=False)

    class Meta:
        model = Team
        fields = ['name', 'city', 'stadium']
        

class NewTeamForm(forms.ModelForm):
    city = forms.ModelChoiceField(queryset=Ciudad.objects.all(), required=False)
    stadium = forms.ModelChoiceField(queryset=Estadio.objects.all(), required=False)

    class Meta:
        model = Team
        fields = ['name', 'city', 'stadium']


#FORM CIUDAD
class UpdateCiudadForm(forms.ModelForm):
    class Meta:
        model = Ciudad
        fields = ["id_ciudad", "name"]


class NewCiudadForm(forms.ModelForm):
    class Meta:
        model = Ciudad
        fields = ["id_ciudad", "name"]


#FORM ESTADIO
class UpdateEstadioForm(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = ["id_estadio", "name"]

class NewEstadioForm(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = ["id_estadio", "name"]

home/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from .models import Team, Ciudad, Estadio
from .forms import UpdateTeamForm, NewTeamForm, UpdateCiudadForm, NewCiudadForm, UpdateEstadioForm, NewEstadioForm

#VIEW EQUIPO

#DETAIL
class DetailTeam(generic.DetailView):
    template_name = "home/teams/detail_equipo.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "equipo": Team.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)


#DELETE
class DeleteTeam(generic.DeleteView):
    template_name = "home/teams/delete_equipo.html"
    model = Team
    success_url = reverse_lazy("home:equipoindex") 


#CREATE
class NewTeam(generic.CreateView):
    template_name = 'home/teams/new_equipo.html'
    model = Team
    form_class = NewTeamForm
    success_url = reverse_lazy('home:teamindex')


#UPDATE
class UpdateTeam(generic.UpdateView):
    template_name = 'home/teams/update_equipo.html'
    model = Team
    form_class = UpdateTeamForm
    success_url = reverse_lazy("home:teamindex")


#PLANTILLA HOME/TEAMINDEX
class TeamIndex(generic.View):
    template_name = "home/teams/teamindex.html"
    context = {}

    def get(self, request):
        self.context = {
            "equipos": Team.objects.all()
        }
        return render(request, self.template_name, self.context)


class EquipoIndex(generic.View):
    template_name = "base/equipoindex.html"
    context = {}

    def get(self, request):
        return render(request, self.template_name, self.context)


class Index(generic.View):
    template_name = "base/lobby.html"
    context = {}

    def get(self, request):
        return render(request, self.template_name, self.context)


#CIUDADES

class DetailCiudad(generic.DetailView):
    template_name = "home/cities/detail_ciudad.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "ciudad": Ciudad.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)


class DeleteCiudad(generic.DeleteView):
    template_name = "home/cities/delete_ciudad.html"
    model = Ciudad
    success_url = reverse_lazy("home:ciudadindex") 

class NewCiudad(generic.CreateView):
    template_name = 'home/cities/new_ciudad.html'
    model = Ciudad
    form_class = NewCiudadForm
    success_url = reverse_lazy('home:ciudadindex')


class UpdateCiudad(generic.UpdateView):
    template_name = 'home/cities/update_ciudad.html'
    model = Ciudad
    form_class = UpdateCiudadForm
    success_url = reverse_lazy("home:ciudadindex")


class CityIndex(generic.View):
    template_name = "home/cities/cityindex.html"
    context = {}

    def get(self, request):
        self.context = {
            "ciudads": Ciudad.objects.all()
        }
        return render(request, self.template_name, self.context)

#ESTADIOS

class DetailEstadio(generic.DetailView):
    template_name = "home/stadiums/detail_estadio.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "estadio": Estadio.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)


class DeleteEstadio(generic.DeleteView):
    template_name = "home/stadiums/delete_estadio.html"
    model = Estadio
    success_url = reverse_lazy("home:estadioindex") 


class NewEstadio(generic.CreateView):
    template_name = 'home/stadiums/new_estadio.html'
    model = Estadio
    form_class = NewEstadioForm
    success_url = reverse_lazy('home:estadioindex')


class UpdateEstadio(generic.UpdateView):
    template_name = 'home/stadiums/update_estadio.html'
    model = Estadio
    form_class = UpdateEstadioForm
    success_url = reverse_lazy("home:estadioindex")


class StadiumIndex(generic.View):
    template_name = "home/stadiums/stadiumindex.html"
    context = {}

    def get(self, request):
        self.context = {
            "estadios": Estadio.objects.all()
        }
        return render(request, self.template_name, self.context)


#////////////////////////////////////////////////////////////////////////////////
#CONSULTAS QUE SE ENCUENTRAN EN EL MENU DE DESPLIEGUE DESDE LA PAGINA WEB


#Ciudades con equipos:
class CityWithTeams(generic.View):
    template_name = "home/teams/citywithteams.html"
    context = {}

    def get(self, request):
        self.context = {
            "ciudades": Ciudad.objects.filter(equipo__isnull=False).distinct()
        }
        return render(request, self.template_name, self.context)


#Que equipo juega en que estadio:
class TeamStadium(generic.View):
    template_name = "home/teams/teamstadium.html"
    context = {}

    def get(self, request):
        self.context = {
            "teams": Team.objects.select_related('stadium')
        }
        return render(request, self.template_name, self.context)


#Que equipos tienen una ciudad:
class CityTeams(generic.View):
    template_name = "home/teams/cityteams.html"
    context = {}

    def get(self, request):
        self.context = {
            "ciudades": Ciudad.objects.exclude(equipo__isnull=True).distinct()
        }
        return render(request, self.template_name, self.context)

templates/home/cities/cityindex.html
{% extends 'base/equipoindex.html' %}
{% block title %} Ciudades {% endblock title %}

{% block content %}
    <div class="d-flex justify-content-end align-items-center">
        <a href="{% url 'home:ciudad_new' %}" class="btn btn-danger">Agregar Ciudad</a>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>Nombre de la Ciudad</th>
            <th>Acciones</th>

        </thead>
        <tbody>
            {% for ciudad in ciudads %}
                <tr>
                    <td>{{ ciudad.id_ciudad }}</td>
                    <td>{{ ciudad.name }}</td>
                    <td><a href="{% url 'home:ciudad_detail' ciudad.id_ciudad %}" class="btn btn-outline-info">Detail</a>
                    <a href="{% url 'home:ciudad_edit' ciudad.id_ciudad %}" class="btn btn-outline-warning">Update</a>
                    <a href="{% url 'home:ciudad_delete' ciudad.id_ciudad %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>    
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/home/cities/delete_ciudad.html
{% extends 'base/equipoindex.html' %}

{% block title %}Delete Ciudad View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Realmente deseas eliminar esta ciudad: {{ object }}?
        <a href="{% url 'home:ciudadindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock content %}

templates/home/cities/detail_ciudad.html
{% extends 'base/equipoindex.html' %}
{% block title %}Detail Ciudad View{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ ciudad.name }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The Category was created by: <strong>{{ ciudad.id_ciudad }}</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the The city is is: <strong><code>{{ ciudad.name }}</code></strong>, though the transition does limit overflow. <a href="{% url 'home:ciudadindex' %}" class="btn btn-link">back to index</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/home/cities/new_ciudad.html
{% extends 'base/equipoindex.html' %}

{% block title %}New Ciudad View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:ciudadindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-success">New Ciudad</button>
    </form>
{% endblock content %}

templates/home/cities/update_ciudad.html
{% extends 'base/equipoindex.html' %}

{% block title %}Update Ciudad View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:ciudadindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-warning">Update</button>
    </form>
{% endblock content %}